// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZXVMst18PQ3XA3SUpVopPHwZxMkIGWA',
    appId: '1:991082664037:web:63fd8bc4689400cbe4b68c',
    messagingSenderId: '991082664037',
    projectId: 'saferoute-ai-7a339',
    authDomain: 'saferoute-ai-7a339.firebaseapp.com',
    storageBucket: 'saferoute-ai-7a339.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkf5JbYDVLzr0YYONCDWC9vdYR9RfusbQ',
    appId: '1:991082664037:android:2d11d141794d543be4b68c',
    messagingSenderId: '991082664037',
    projectId: 'saferoute-ai-7a339',
    storageBucket: 'saferoute-ai-7a339.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjZXVMst18PQ3XA3SUpVopPHwZxMkIGWA',
    appId: '1:991082664037:web:c3d99b9dd7049f65e4b68c',
    messagingSenderId: '991082664037',
    projectId: 'saferoute-ai-7a339',
    authDomain: 'saferoute-ai-7a339.firebaseapp.com',
    storageBucket: 'saferoute-ai-7a339.firebasestorage.app',
  );
}
